### ISSUE TITLE
Feature request: Please add appVersion to Chart object 

### ISSUE THREAD

**Issue by ocarlsen** [quintush/helm-unittest#100]
Liking library very much.  However, we utilize `Chart.appVersion` in our templates, but this cannot be set when running unit tests.  

Please add `appVersion` to `Chart` object in [Test Suite](https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md#test-suite).

**Comment by quintush** [comment]
Hello @ocarlsen,

Thanks for the feedback.
I will add it as a feature.

greetings,
@quintush
