### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by renehernandez** [quintush/helm-unittest#105]
Can we get a new version released?

I need that in order to work on the helmfile integration.

**Comment by quintush** [comment]
Hello @renehernandez,

I'm planning to create release 0.2.6 not later than april 1st (no april fools Joke 😂)
Still working on the last feature request.

Greetings,
@quintush

**Comment by ocarlsen** [comment]
Hey @quintush ,

Is there any way to view the current version I have installed?  I tried to confirm [this feature](https://github.com/quintush/helm-unittest/pull/103) but its not working yet.  Then I wondered if I had the latest version?  It says 0.2.6 in `helm plugin list` but then I saw here the release was not made yet.

**Comment by quintush** [comment]
Hello @renehernandez,

Version 0.2.6 is succesfully released, including docker containers on dockerhub.

Greetings and happy easter.
@quintush
