### ISSUE TITLE
Contains assertion type doesn't support annotations map

### ISSUE THREAD

**Issue by leonenkoa** [quintush/helm-unittest#107]
Hi, thank you for the useful plugin.
It seems that contains assertion type doesn't support metadata.annotations map.
Is this due to any limitations ?

**Comment by quintush** [comment]
Hello @leonenkoa,

The contains assertion is expecting an array.
The map is technicaly not an array. That is why the contains is not working.

You can validate maps with the equal (which can handle complex structures), or validate if a specific map is available with IsNull.

I also will look on creating a containsMap assertion to validate if a specific map, with value is available.

Greetings,
@quintush

**Comment by gcavalcante8808** [comment]
Hey @quintush, do you have an example with isnull and a map assertion? I’m
looking for it as well.

**Comment by quintush** [comment]
Hello @gcavalcante8808 ,

As a quick answer, 
Take a look at the [ingress tests](https://www.github.com/quintush/helm-unittest/tree/master/test%2Fdata%2Fv3%2Fbasic%2Ftests%2Fingress_test.yaml#L54).
It will not have the IsNull, but it does show how to select a specific map.

Greetings,
@quintush

**Comment by quintush** [comment]
Hello @gcavalcante8808,

I have created some examples with mappings.
https://github.com/quintush/helm-unittest/blob/71544f7a30e97d280545da8cd5ba61b27d28f75c/test/data/v3/basic/tests/ingress_test.yaml#L72

Hopefully this will help.

Greetings,
@quintush 



>
