### ISSUE TITLE
Assert equals without hardcoding values

### ISSUE THREAD

**Issue by plentifullee** [quintush/helm-unittest#122]
Say I want check whether a value equals another value:

- equal:
          path: spec.template.spec.containers[0].livenessProbe.periodSeconds
          value: spec.template.spec.containers[0].readinessProbe.periodSeconds

The above doesn't work

`- asserts[5] `equal` fail
			Template:	testa/templates/deployment.yaml
			DocumentIndex:	0
			Path:	spec.template.spec.containers[0].livenessProbe.periodSeconds
			Expected to equal:
				spec.template.spec.containers[0].readinessProbe.periodSeconds
			Actual:
				10
			Diff:
				--- Expected
				+++ Actual
				@@ -1,2 +1,2 @@
				-spec.template.spec.containers[0].readinessProbe.periodSeconds
				+10`

Is it possible to do it without hardcoding the 'value' or is there another work around?

**Comment by quintush** [comment]
Hello @plentifullee ,

It is not possible to use the output of a path as value for another path.

When you would like to have always the same value for multiple paths, i would recommend to set the helm chart to re-use a field defined in the values.yaml.

Greetings,
@quintush
