### ISSUE TITLE
Ownership of the original repo

### ISSUE THREAD

**Issue by krichter722** [quintush/helm-unittest#124]
@quintush, your doing a fantastic job in maintaining and developing this tool that is so desperately needed in a world with so many charts and so few unit tests for them.

Did you consider taking over the original repo https://github.com/helm-unittest/helm-unittest which is already recommending your fork as more up-to-date?

> warning THIS REPOSITORY IS NOT MAINTAINED ANYMORE. warning
>
> You can consider other working forks like quintush/helm-unittest. If anyone would like to continue maintaining this repo, please mail zeldalink0515@gmail.com. I'd be glad to transfer ownership and see it live again.

It's a bit of responsibility that you've basically already taken over and would make things much more easy to and accessible.

**Comment by quintush** [comment]
Hello @krichter722 ,

I do have contact with the original maintainer and we are making preparations to merge both repositories.
Still i'm looking for a good opportunity to make it happen.

Greetings,
@quintush
