### ISSUE TITLE
Bug with helm v3: templating error messages parsing error

### ISSUE THREAD

**Issue by mederel** [quintush/helm-unittest#144]
Hi,

recently my unittests started to fail on asserts with failedTemplate and errorMessage expectations. The test was outing something like that:

```
 FAIL  Custom configuration     test/tests/configmap_test.yaml
        - should fail

                - asserts[0] `failedTemplate` fail
                        Error:
                                template "skube-kstream-chart/templates/deployment.yaml" not exists or not selected in test suite
```

Looking into it is actually the regular expression that parses the helm error messages that does not work anymore for helm v3.

I opened a pull request with a fix proposal. I added also tests on V3 of failedTemplate validation.

Best regards, Emile

**Comment by bamsammich** [comment]
Running into this same error trying to test against JSON schema validation with Helm3. @quintush will this be looked at/merged soon?
