### ISSUE TITLE
How can i run helm-unittests in Jenkins?

### ISSUE THREAD

**Issue by kishkk84** [quintush/helm-unittest#148]
Hi all,

We have many charts in the repo and i am writing helm-unitests in each and every chart. Whenever any engineer makes any changes to the chart & commits it, i want to run the jenkins pipeline which will run the helm-unittests. Any idea how can i target only the changes made to the chart runs unittests?

Here is my set up in the repo:

platform-charts
- application-charts
  - Chart 1
    - tests
      - *_test.yaml
      - *_test.yaml
  - Chart 2
     - tests
       - *_test.yaml
       - *_test.yaml 
  - Chart 3
     - tests 
       - *_test.yaml
       - *_test.yaml

**Comment by B3arp** [comment]
Something like this should give you a list of all charts that changed, and you can loop through it to unit test. 

`git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }'  | awk -F/ '{print $1"/"$2}' | sort | uniq`

**Comment by B3arp** [comment]
@kishkk84 Sorry for the delay, life happened.  Here is an example of running this through jenkins.  This will generate a list of folders that have changed and then passes the chart roots to helm unit-test
`git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | awk -F/ '{print $1"/"$2}' | sort | uniq | xargs helm unittest -3`

**Comment by quintush** [comment]
Hello @kishkk84, @B3arp,

Another way is to use the below options, which generates testresults in a file format that can be read by most of the buildservers (like jenkins).
  -t, --output-type string     the file-format where testresults are written in, accepted types are (JUnit, NUnit, XUnit) (default XUnit)
  -o, --output-file string     the file where testresults are written in format specified, defaults no output is written to file

```
$ helm helm-unittest ... -t JUnit -o junit-results.xml
```
