### ISSUE TITLE
[feature] Add assertion for count items in list.

### ISSUE THREAD

**Issue by eshepelyuk** [quintush/helm-unittest#152]
Hello

Currently there is no way to assert that a list contains certain number of elements.

Maybe it could be usuful for the maps as well, ike metadata annotations.

**Comment by rquinio** [comment]
There's a "contains" assertion https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md?plain=1#L174 , not sure if it's only for arrays?

**Comment by eshepelyuk** [comment]
` contains` is not suitable, it can not answer if partifular array / map has exact N number of items / keys.

**Comment by eshepelyuk** [comment]
In fact, I am ready to pick up this and try to implement.

**Comment by lsolovey** [comment]
@eshepelyuk How did you resolve this issue?

**Comment by eshepelyuk** [comment]
> @eshepelyuk How did you resolve this issue?

nohow,i just closed the issue ,since it have been ignored.

**Comment by lsolovey** [comment]
> > @eshepelyuk How did you resolve this issue?
> 
> nohow,i just closed the issue ,since it have been ignored.

I see. @quintush could you please reopen this issue, I think it's still a valid feature request.
