### ISSUE TITLE
Support for array filtering in paths

### ISSUE THREAD

**Issue by rquinio1A** [quintush/helm-unittest#158]
Instead of 

```yaml
- matchRegex:
      path: spec.template.spec.containers[0].env[2].value
```

it would be more maintainable to filter on the properties of the array elements:

```yaml
- matchRegex:
      path: spec.template.spec.containers[0].env[@name==JAVA_OPTS].value
```

Even better would be to replacing the custom path traversal implementation (https://github.com/quintush/helm-unittest/blob/master/pkg/unittest/valueutils/valueutils.go#L156) by a dedicated lib.

There seems to be 2 standards:
- JSON-path, implementation:  https://github.com/vmware-labs/yaml-jsonpath
- YAML-path (https://github.com/wwkimball/yamlpath)  - not sure if there's a go implementation?

**Comment by quintush** [comment]
Feature is implemented in version v0.3.0 available in the main [helm-unittest/helm-unittest](https://github.com/helm-unittest/helm-unittest) repo.

Greetings,
@quintush
