### ISSUE TITLE
[question] Is this repository / project dead ?

### ISSUE THREAD

**Issue by eshepelyuk** [quintush/helm-unittest#170]
Hello

Waht is the status of the project ? There is a number of useful PR open without feedback provided for several monthes.

If this project has no maintainers that are willing to continue working on it - maybe there exist some active forks that can be used ?

Please suggest.

**Comment by vutkin** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/25753488/180206840-3d8cac83-cf7a-4ed7-bdde-c16e60283237.png">
 Looks like a dead project

**Comment by d3adb5** [comment]
That's pretty unfortunate. Are there actively maintained forks? Skimmed the list a while back, but didn't look into it very closely. It's somewhat depressing given I've started using this for testing Helm charts in a few projects recently and found a few bugs I was hoping would be fixed sometime soon. Not a Go developer, but might take matters into my own hands at some point.

**Comment by mballoni** [comment]
Agree!

I few there is a lack of maintained testing projects aiming helm charts.

**Comment by quintush** [comment]
Will pick-up beginning of next month. Will have some more time, and will also move to a more central repo, to add more maintainers.

Sorry die the delay in responding.

Greetings,
@quintush

**Comment by mballoni** [comment]
Thanks @quintush , no need to apologise, its your free time and we appreciate your efforts!

**Comment by quintush** [comment]
Hello all,

Will pick it up again. Indeed it took some time.
As a quick update i have approved some pullrequests, that do have a lot of benefits, don't have a huge impact, so a new updated version is quickly available.

Greetings,
@quintush
