### ISSUE TITLE
[bug] No download_url found only searching for linux

### ISSUE THREAD

**Issue by hairmare** [quintush/helm-unittest#195]
The newly published [version 0.2.11](https://github.com/quintush/helm-unittest/releases/tag/v0.2.11) is missing assets and can't be installed:

```console
$ helm plugin install https://github.com/quintush/helm-unittest
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.2.11
No download_url found only searching for linux
```

The workaround seems to be removing the plugin and reinstalling a specific version that works:

```bash
helm plugin uninstall unittest
helm plugin install https://github.com/quintush/helm-unittest --version 0.2.10
```

Helm version: 3.10.3 (latest security patch release from 3 weeks ago)

**Comment by quintush** [comment]
Hello @hairmare,

Uploading of the artifacts failed, fixed the upload now.

Greetings,
@quintush

**Comment by hairmare** [comment]
Hey @quintush 

Thank you very much!
