### ISSUE TITLE
:bug: Problem installing helm-unittest on linux-amd64

### ISSUE THREAD

**Issue by thiago-scherrer** [quintush/helm-unittest#203]
When trying to install helm-unittest using the command `helm plugin install https://github.com/quintush/helm-unittest` I am encountering an error that prevents installation on linux-amd64. Here's the error message:

```sh
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.3.0
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.3.0/helm-unittest-linux-amd64-0.2.11.tgz https://github.com/quintush/helm-unittest/releases/download/v0.3.0/helm-unittest-linux-amd64-0.3.0.tgz to location /tmp/_dist/
curl: Failed to extract a sensible file name from the URL to use for storage!
curl: (3) URL using bad/illegal format or missing URL
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
```

I have tried this on multiple linux-amd64 with helm v3.11.2 or 3.9.0 and encountered the same error. This started with version v0.3.0 :thinking: 

Thanks.

**Comment by aroberts87** [comment]
I was just coming here to report the same thing. 🙂 A quick workaround we're using is to pin the install to the previous version.
```
helm plugin install https://github.com/quintush/helm-unittest --version=0.2.11
```

**Comment by trmiller** [comment]
Can confirm - same issue, and same workaround.  It appears the latest release points to two versions at the same time, causing the download error

**Comment by quintush** [comment]
Removed the 0.3.0 release, as it should not have been set.
The install should work now without the version pinning.

**Comment by thiago-scherrer** [comment]
> Removed the 0.3.0 release, as it should not have been set. The install should work now without the version pinning.

I just tested it without the version pinning and it worked!! Thank you!
