### ISSUE TITLE
Dockerhub image

### ISSUE THREAD

**Issue by aneesh-joseph** [quintush/helm-unittest#33]
Thank you for forking and improving this one. Can you publish this to dockerhub please :)

**Comment by quintush** [comment]
I will look into this.

**Comment by quintush** [comment]
Hello @aneesh-joseph ,

As requested i have published the plugin on dockerhub with several combinations helm client versions.
After each update of the plugin, the latest plugin in combination with several versions of helm will be published.

Greetings,
Quintus van Houdt
