### ISSUE TITLE
shasum not working on alpine docker images

### ISSUE THREAD

**Issue by sascha-krug** [quintush/helm-unittest#35]
Hi,

we are using your plugin on some docker images based on a google/cloud-sdk:alpine image. Sadly it does not contain "shasum".

So while installing the plugin this occurs:

`Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.0/helm-unittest-linux-amd64-0.2.0.tgz to location /tmp/_dist/
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
 100   648  100   648    0     0   9529      0 --:--:-- --:--:-- --:--:--  9529
 100 16.9M  100 16.9M    0     0  9483k      0  0:00:01  0:00:01 --:--:-- 15.0M
 Validating Checksum.
 ./install-binary.sh: line 120: shasum: command not found`

But sha1sum, sha256sum, sha3sum, sha512sum are available.

So maybe is it possible to check if shasum is existing and if not then maybe use one of the above?

Cheers,
Sascha

**Comment by quintush** [comment]
I will look into that.

Will try to use sha256sum if shasum is nog available.
