### ISSUE TITLE
strange issue with helm3 chart unittests

### ISSUE THREAD

**Issue by Scoi4101** [quintush/helm-unittest#39]
Getting this error on most of my tests that work fine in helm 2.9.1

assertion.template must be given if testsuite.templates is empty

Helm 3.1.2 and Helm 3.2.3 have the same issue.

So i pulled your repo and ran the same templates and tests in your repo and they pass

Any thoughts would be appreciated

**Comment by quintush** [comment]
Which version of the plugin did you use?

In newer versions 0.2.0+, i have made sone improvements where it is possible set the template on multiple levels.

Greetings, @quintush

**Comment by Scoi4101** [comment]
Hello,

Thanks or the response.

helm plugin list
NAME            VERSION DESCRIPTION                                                                         
unittest        0.2.1   Unit test for helm chart in YAML with ease to keep your chart functional and robust.

The super weird thing is that I have downloaded your repo and copied a test, value file, etc and it runs with no issue.
