### ISSUE TITLE
Install fails on MacOS because /etc/os-release does not exist

### ISSUE THREAD

**Issue by mydimension** [quintush/helm-unittest#82]
Took me a while to track this down. The install command and output look like this:

```
$❯ helm plugin install https://github.com/quintush/helm-unittest --version 0.2.5
Support macos-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.2.5
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.5/helm-unittest-macos-amd64-0.2.5.tgz to location /tmp/_dist/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   661  100   661    0     0   4105      0 --:--:-- --:--:-- --:--:--  4105
100 17.2M  100 17.2M    0     0  12.4M      0  0:00:01  0:00:01 --:--:-- 18.5M
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
```

Stepping through `install-binary.sh` I noted that the `cat` command will ultimately fail on MacOS:

```
$❯ cat /etc/os-release
cat: /etc/os-release: No such file or directory
```

And causes the whole script to fail.

https://github.com/quintush/helm-unittest/blob/778bc25bf69d8d22508faf1a1beb460d05255f3a/install-binary.sh#L115

**Comment by quintush** [comment]
Hello @mydimension,

Thanks for the feedback.
I was assuming the 2>&1 purged the error.
My bad, never assume something...

I will try to fix it as soon as possible and will release a new version of 0.2.5.

Greetings @quintush

**Comment by quintush** [comment]
Hello @mydimension,

Thanks for the feedback.
I was assuming the 2>&1 purged the error.
My bad, never assume something...

I will try to fix it as soon as possible and will release a new version of 0.2.5.

Greetings @quintush
