### ISSUE TITLE
add feature to failFast

### ISSUE THREAD

**Issue by uniqueck** [quintush/helm-unittest#84]
Hi,

is it possible to have something like this.

If something goes completely wrong, it would be nice to have an option that stops right after the first error.
So it is easier to find the error, maybe something like template not found, or something else.

**Comment by quintush** [comment]
Hello @uniqueck,

Thanks for the feedback.
I will try to add the failfast as an flag.

I also noticed the errorhandling can be improved.

Greetings @quintush
