### ISSUE TITLE
[feat] Ability to select elements (jq style) rather than just dot and bracket notation.

### ISSUE THREAD

**Issue by naphta** [quintush/helm-unittest#85]
Just started with this plugin and the most immediate thing I've noticed is that the path selections can be a little bit restrictive, mainly around testing outputs of loops where you essentially need to test the element before and after to make sure nothing has actually changed. I'm thinking jmespath or jq would expand the usability a fair bit for example:

```
      - equal:
          path: spec.template.spec.containers[0].env[3].name
          value: APPCONFIG__RABBITSETTINGS__HOSTS__0
```
vs
```
      - equal:
          path: spec.template.spec.containers[?name == `default`].env[?name == APPCONFIG__RABBITSETTINGS__HOSTS__0].value
          value: value
```
vs
```
      - equal:
          path: spec.template.spec.containers | select(.name == "default").env | select(.name == "APPCONFIG__RABBITSETTINGS__HOSTS__0").value
          value: value
```

Very loose examples, but I think being able to select by container etc would make some of the testing a lot less verbose at times, although certainly harder to read for those unversed in such things. (I've not tested these are legitimate against JSON)

**Comment by quintush** [comment]
Hello @naphta,

Thanks for the feedback.
I will look into the option of expanding the patch filters, however it van taken some time, as the path is parsed letter-by-letter.

Greetings @quintush

**Comment by thib92** [comment]
I have run into it as well.
using a lib like [gojq](https://github.com/itchyny/gojq) might help with this implementation. I haven't looked at how the path selector is implemented on `helm-unittest` yet.

**Comment by naphta** [comment]
> 
> 
> I have run into it as well.
> using a lib like [gojq](https://github.com/itchyny/gojq) might help with this implementation. I haven't looked at how the path selector is implemented on `helm-unittest` yet.
> 
> Though it seems like the current validators' code implies that the `path` always point to a single value (which seems fair), whereas a JSONPath or a jq-style path could result in multiple values.

That's true but is that not more of a hidden feature?

`x.y.z` returns a an object which can then be compared to an object.
