### ISSUE TITLE
Tests fail if a chart uses include()

### ISSUE THREAD

**Issue by sereinity** [quintush/helm-unittest#94]
Hello,

## what I wanted to do
I wanted to perform tests on one of my charts that has bitnami/redis as a dependency, I can't test some of document because the generation fails (only when running unittest).

My investigations shows that the issue could occurs to a lot of other charts.

## reproducing

This fails because the chart uses an include statement (to add a checksum in an annotations, which is something many people do to ensure a pod is recreated if a configmap change).

To reproduce I patched:
```patch
diff --git a/test/data/v3/basic/templates/deployment.yaml b/test/data/v3/basic/templates/deployment.yaml
index 2820188..e72f8f2 100644
--- a/test/data/v3/basic/templates/deployment.yaml
+++ b/test/data/v3/basic/templates/deployment.yaml
@@ -15,6 +15,8 @@ spec:
       labels:
         app: {{ template "basic.name" . }}
         release: {{ .Release.Name }}
+      annotations:
+        checksum/health: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
     spec:
       containers:
         - name: {{ .Chart.Name }}
```

`helm template` still works fine, but not unittest:
```

### Chart [ basic ] .

 PASS  Configmap mulit line Test        tests/configmap_test.yaml
 PASS  Custom Resource Definition Test  tests/crd_test.yaml
 FAIL  test deployment  tests/deployment_test.yaml
        - should pass all kinds of assertion

                - asserts[0] `equal` fail
                        Template:       basic/templates/deployment.yaml
                        DocumentIndex:  0
                        Error:
                                can't get ["template"] from a non map type:
                                null
[… removing a lot of errors]
2021/03/17 15:50:38 warning: destination for annotations is a table. Ignoring non-table value <nil>
2021/03/17 15:50:38 warning: destination for annotations is a table. Ignoring non-table value <nil>
2021/03/17 15:50:38 warning: destination for annotations is a table. Ignoring non-table value <nil>
2021/03/17 15:50:38 warning: destination for annotations is a table. Ignoring non-table value <nil>
 PASS  test ingress     tests/ingress_test.yaml
 PASS  test notes       tests/notes_test.yaml
 PASS  test service     tests/service_test.yaml

Snapshot Summary: 1 snapshot failed in 1 test suite. Check changes and use `-u` to update snapshot.

Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 5 passed, 6 total
Tests:       1 failed, 13 passed, 14 total
Snapshot:    1 failed, 3 passed, 4 total
Time:        8.533923ms

Error: plugin "unittest" exited with error
```

**Comment by quintush** [comment]
Hello @sereinity,

Thanks for the feedback.
I took a quick look what is causing the error (as the rendering of the charts is done exacly the same way as the template) and found the reason.

To minimize the impact of unittesting, only the templates rendered that are part of the unittest, instead of rendering all templates of the chart. This results in a failure due to a missing template.

Feel free to have some suggestions on how to solve this issue.

Greetings,
@quintush

**Comment by sereinity** [comment]
My first step would be to catch the error and print something useful, by example right now unittest detects that there is 1 document when it fails.

If we can have an helpful error message, we could determine what the missing template is, and render it before retrying to render the first template; recursively.

I don't know if it's better (perf, other misbehave) to render all or only partially. I think we can found out by trying :)

**Comment by quintush** [comment]
Hello @sereinity ,

Thanks for the update and the suggestions.

Currently i have created a fix, which has a better identification of an unexpected failure (see https://github.com/quintush/helm-unittest/blob/c68b9673a8bac20c4f4653d2043aef836c161b91/pkg/unittest/.snapshots/TestV3RunnerOkWithFailedTests#L280 as the result of your testscenario).

I will additionally document that the chart will only render the files, defined in the templates.
Reasoning behind the partially rendering is not of performance, but more of isolation. e.g. when specific template require additional input, you can choose to not test the template, or add set values to the unittest, that don't relate to the template you are testing. Also this is also the original behaviour of the plugin.

Greetings,
@quintush
